apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  type: NodePort # Exposes the service on a static port on the cluster node
  selector:
    app: product-api # This must match the label in the deployment's template
  ports:
    - protocol: TCP
      port: 80       # Port inside the cluster
      targetPort: 6000 # Port on the pod/container
