name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-apigee-proxy:
    name: Deploy Product Catalog Proxy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # This step sets up gcloud AND installs the beta components correctly
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'beta'

      # Install jq in a separate clean step
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Zip the API Proxy bundle
        run: |
          cd ./product-catalog-v1
          zip -r ../proxy.zip . -x "*.DS_Store"

      # STEP 1: Import the new bundle via the Apigee REST API to create a new revision
      - name: Import Bundle via API to Create New Revision
        id: import
        run: |
          TOKEN=$(gcloud auth print-access-token)
          
          IMPORT_OUTPUT=$(curl -s -X POST "https://apigee.googleapis.com/v1/organizations/${{ secrets.GCP_APIGEE_ORG }}/apis?action=import&name=product-catalog-v1" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary "@proxy.zip")
            
          echo "API Response: $IMPORT_OUTPUT"
          NEW_REVISION=$(echo "$IMPORT_OUTPUT" | jq -r '.revision')
          echo "Discovered new revision: $NEW_REVISION"
          echo "revision_id=$NEW_REVISION" >> "$GITHUB_OUTPUT"

      # STEP 2: Deploy the newly created revision using --override for zero-downtime
      - name: Deploy New Revision with Zero Downtime
        run: |
          gcloud apigee apis deploy ${{ steps.import.outputs.revision_id }} \
            --api="product-catalog-v1" \
            --environment="eval" \
            --organization="${{ secrets.GCP_APIGEE_ORG }}" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --override
