name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-apigee-proxy:
    name: Deploy Product Catalog Proxy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      # Step 1: Zip the API Proxy bundle. This is unchanged and works.
      - name: Zip the API Proxy bundle
        run: |
          cd ./product-catalog-v1
          zip -r ../proxy.zip . -x "*.DS_Store"

      # Step 2: Deploy the zipped bundle. This command is now corrected.
      - name: Deploy API Proxy from Zip
        run: |
          gcloud apigee apis deploy "product-catalog-v1" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --organization="${{ secrets.GCP_APIGEE_ORG }}" \
            --environment="eval" \
            --source="proxy.zip"
