name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-apigee-proxy:
    name: Deploy Product Catalog Proxy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This auth step is still required for the deploy action to authenticate
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # This is the ONLY step needed for deployment.
      # It replaces all the 'gcloud', 'zip', and 'install' steps.
      - name: Deploy Apigee proxy using Google's official Action
        uses: google-github-actions/deploy-apigee-proxy@v1
        with:
          proxy_name: 'product-catalog-v1'
          directory: './product-catalog-v1'
          environment: 'eval'
          gcp_project_id: '${{ secrets.GCP_PROJECT_ID }}'
          gcp_organization_id: '${{ secrets.GCP_APIGEE_ORG }}'
