name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-apigee-proxy:
    name: Deploy Product Catalog Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Install gcloud beta components
        run: gcloud components install beta --quiet

      # <<< NEW STEP ADDED HERE >>>
      - name: Zip the API Proxy bundle
        run: |
          cd ./product-catalog-v1
          zip -r ../proxy.zip . -x "*.DS_Store"

      # <<< DEPLOYMENT STEP CORRECTED HERE >>>
      - name: Deploy API Proxy to eval environment
        run: |
          gcloud apigee apis deploy "product-catalog-v1" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --organization="${{ secrets.GCP_APIGEE_ORG }}" \
            --environment="eval" \
            --service-account-from-file="${{ steps.auth.outputs.credentials_file_path }}" \
            --import=proxy.zip
